# Generated by Django 2.0.4 on 2018-04-29 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Figurinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tenho', models.BooleanField(default=True)),
                ('brilhante', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de figurinhas repetidas')),
                ('data', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de modificação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Figurinha',
                'verbose_name_plural': 'Figurinhas',
                'ordering': ['id'],
            },
        ),
    ]
